WITH CTE AS
(
	SELECT
		EXP.*,EDU.DEGREE,TRIM(REPLACE(REPLACE(REPLACE(Title,'Sr.','Senior'),"Finance","Financial"),'Sr ','Senior ')) AS SIMPLIFIED_TITLE
	FROM 
		MBA_SCRAPING.mba_profiles_all EXP
	LEFT JOIN 
		mba_scraping.MBA_PROFILES_EDUCATION EDU
	ON 
		EXP.HANDLE=EDU.HANDLE
	WHERE
		EDU.HANDLE IS NOT NULL
),
CTE_INDICATORS AS 
(
SELECT
	*
    ,CASE 
		WHEN UPPER(TITLE) LIKE '%DIRECTOR%' OR
			 UPPER(TITLE) LIKE '%DIRECTOR' OR
			 UPPER(TITLE) LIKE 'DIRECTOR%' OR
             UPPER(TITLE) LIKE 'DIRECTOR'
        THEN 'Director'
        WHEN UPPER(TITLE) LIKE '%ANALYST%' OR
			 UPPER(TITLE) LIKE 'ANALYST' OR
             UPPER(TITLE) LIKE '%ANALYST' OR
             UPPER(TITLE) LIKE 'ANALYST%'
        THEN 'Analyst'
        WHEN UPPER(TITLE) LIKE '%ASSOCIATE%' OR
			 UPPER(TITLE) LIKE 'ASSOCIATE' OR
             UPPER(TITLE) LIKE 'ASSOCIATE%' OR
             UPPER(TITLE) LIKE '%ASSOCIATE' 
        THEN 'Associate'
        WHEN UPPER(TITLE) LIKE '%MANAGER%' OR
			 UPPER(TITLE) LIKE 'MANAGER' OR
             UPPER(TITLE) LIKE 'MANAGER%' OR
             UPPER(TITLE) LIKE '%MANAGER' 
        THEN 'Manager'
        WHEN UPPER(TITLE) LIKE '%PARTNER%' OR
			 UPPER(TITLE) LIKE 'PARTNER' OR
             UPPER(TITLE) LIKE 'PARTNER%' OR
             UPPER(TITLE) LIKE '%PARTNER' 
        THEN 'Partner'
        WHEN UPPER(TITLE) LIKE '%PRESIDENT%' OR
			 UPPER(TITLE) LIKE 'PRESIDENT' OR
             UPPER(TITLE) LIKE 'PRESIDENT%' OR
             UPPER(TITLE) LIKE '%PRESIDENT' 
        THEN 'President'
        WHEN UPPER(TITLE) LIKE '%HEAD%' OR
			 UPPER(TITLE) LIKE 'HEAD' OR
             UPPER(TITLE) LIKE 'HEAD%' OR
             UPPER(TITLE) LIKE '%HEAD' 
        THEN 'Head'
        WHEN UPPER(TITLE) LIKE '%LEAD%' OR
			 UPPER(TITLE) LIKE 'LEAD' OR
             UPPER(TITLE) LIKE 'LEAD%' OR
             UPPER(TITLE) LIKE '%LEAD' 
        THEN 'Lead'
        ELSE NULL
	END AS role_indicator
    ,CASE 
		WHEN UPPER(DEGREE) LIKE '%FINANCE%' AND UPPER(DEGREE) LIKE '%MARKETING%'
        THEN 'Finance and Marketing'
        WHEN UPPER(DEGREE) LIKE '%FINANCE%' AND UPPER(DEGREE) LIKE '%GENERAL%'
        THEN 'Finance and General Management'
        WHEN UPPER(DEGREE) LIKE '%FINANCE%' AND UPPER(DEGREE) LIKE '%STRATEGY%'
        THEN 'Finance and Strategy'
        WHEN UPPER(DEGREE) LIKE '%MARKETING%' AND UPPER(DEGREE) LIKE '%GENERAL%'
        THEN 'Marketing and General Management'
        WHEN UPPER(DEGREE) LIKE '%MARKETING%' AND UPPER(DEGREE) LIKE '%STRATEGY%'
        THEN 'Marketing and Strategy'
        WHEN UPPER(DEGREE) LIKE '%MARKETING%' 
        THEN 'Marketing'
        WHEN UPPER(DEGREE) LIKE '%FINANCE%'
        THEN 'Finance'
        WHEN UPPER(DEGREE) LIKE '%STRATEGY%'
        THEN 'Strategy'
        WHEN UPPER(DEGREE) LIKE '%GENERAL%'
        THEN 'General'
        WHEN UPPER(DEGREE) LIKE '%TECHNOLOGY MANAGEMENT%'
        THEN 'Technology Management'
        WHEN UPPER(DEGREE) LIKE '%BUSINESS ANALYTICS%'
        THEN 'Business Analytics'
        ELSE 'Not Specified'
	END DEGREE_SPEC
    ,CASE 	
		WHEN UPPER(TITLE) LIKE '%SENIOR%' OR UPPER(TITLE) LIKE 'SR. %' OR '%SVP %'
        THEN 1
        ELSE 0
	END AS SENIOR_INDICATOR
    ,CASE 
		WHEN UPPER(SIMPLIFIED_TITLE) LIKE '%VICE PRESIDENT%' OR 
		     UPPER(SIMPLIFIED_TITLE) LIKE 'VP %' OR 
             UPPER(SIMPLIFIED_TITLE) LIKE 'SVP %' OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'SVP, %' OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'SENIOR VICE PRESIDET%'
        THEN 'Vice President'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'DIRECTOR%' OR
		     UPPER(SIMPLIFIED_TITLE) LIKE 'SENIOR DIRECTOR%' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%DIRECTOR%'  OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'DIRECTOR%' 
        THEN 'Director' 
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'ASSOCIATE'  OR
			 UPPER(SIMPLIFIED_TITLE) LIKE 'SENIOR ASSOCIATE'  
        THEN 'Associate'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'FOUNDER'  OR
			 UPPER(SIMPLIFIED_TITLE) LIKE '%FOUNDER%'  OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'FOUNDER%'  OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%FOUNDER'  
        THEN 'Founder'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'AUDITOR'  OR
			 UPPER(SIMPLIFIED_TITLE) LIKE '%AUDITOR%'  OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'AUDITOR%'  OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%AUDITOR'  OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'AUDIT MANAGER' 
        THEN 'Auditor'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE '%FINANCIAL ANALYST%' OR
			 UPPER(SIMPLIFIED_TITLE) LIKE 'FINANCIAL ANALYST%' OR 
             UPPER(SIMPLIFIED_TITLE) LIKE 'FINANCIAL ANALYST' OR 
             UPPER(SIMPLIFIED_TITLE) LIKE '%FINANCIAL ANALYST' 
		THEN 'Financial Analyst'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE '%PRODUCT MANAGER%' OR
			 UPPER(SIMPLIFIED_TITLE) LIKE 'PRODUCT MANAGER' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%PRODUCT MANAGER' OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'PRODUCT MANAGER%' 
        THEN 'Product Manager'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE '%PROGRAM MANAGER%' OR
			 UPPER(SIMPLIFIED_TITLE) LIKE '%PROGRAM MANAGER' OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'PROGRAM MANAGER%' OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'PROGRAM MANAGER' 
        THEN 'Program Manager'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE '%PROJECT MANAGER%' OR
			 UPPER(SIMPLIFIED_TITLE) LIKE 'PROJECT MANAGER%' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%PROJECT MANAGER' OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'PROJECT MANAGER' 
        THEN 'Project Manager'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'ENGINEERING MANAGER' OR
			 UPPER(SIMPLIFIED_TITLE) LIKE '%ENGINEERING MANAGER%' OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'ENGINEERING MANAGER%' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%ENGINEERING MANAGER' 
		THEN 'Engineering Manager'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'SENIOR MANAGER' OR
			 UPPER(SIMPLIFIED_TITLE) LIKE 'SENIOR MANAGER%' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%SENIOR MANAGER' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%SENIOR MANAGER%' 
		THEN 'Senior Manager'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'FINANCIAL MANAGER' OR
			 UPPER(SIMPLIFIED_TITLE) LIKE 'FINANCIAL MANAGER%' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%FINANCIAL MANAGER' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%FINANCIAL MANAGER%' 
		THEN 'Financial Manager'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'MARKETING MANAGER' OR
			 UPPER(SIMPLIFIED_TITLE) LIKE 'MARKETING MANAGER%' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%MARKETING MANAGER' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%MARKETING MANAGER%' 
		THEN 'Marketing Manager'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'BUSINESS DEVELOPMENT MANAGER' OR
			 UPPER(SIMPLIFIED_TITLE) LIKE 'BUSINESS DEVELOPMENT MANAGER%' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%BUSINESS DEVELOPMENT MANAGER' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%BUSINESS DEVELOPMENT MANAGER%' 
		THEN 'Business Development Manager'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'ASSOCIATE MANAGER' OR
			 UPPER(SIMPLIFIED_TITLE) LIKE 'ASSOCIATE MANAGER%' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%ASSOCIATE MANAGER' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%ASSOCIATE MANAGER%' OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'ASSOCIATE%MANAGER'
		THEN 'Associate Manager'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'CONTROLLER' OR
			 UPPER(SIMPLIFIED_TITLE) LIKE 'CONTROLLER%' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%CONTROLLER' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%CONTROLLER%' 
		THEN 'Controller'
        WHEN (UPPER(SIMPLIFIED_TITLE) LIKE 'QUALITY' AND UPPER(SIMPLIFIED_TITLE) LIKE 'MANAGER') OR 
			 (UPPER(SIMPLIFIED_TITLE) LIKE '%QUALITY' AND UPPER(SIMPLIFIED_TITLE) LIKE '%MANAGER') OR 
             (UPPER(SIMPLIFIED_TITLE) LIKE 'QUALITY%' AND UPPER(SIMPLIFIED_TITLE) LIKE 'MANAGER%') OR 
             (UPPER(SIMPLIFIED_TITLE) LIKE '%QUALITY%' AND UPPER(SIMPLIFIED_TITLE) LIKE '%MANAGER%')
		THEN 'Quality Manager'
        WHEN (UPPER(SIMPLIFIED_TITLE) LIKE 'SALES' AND UPPER(SIMPLIFIED_TITLE) LIKE 'MANAGER') OR 
			 (UPPER(SIMPLIFIED_TITLE) LIKE '%SALES' AND UPPER(SIMPLIFIED_TITLE) LIKE '%MANAGER') OR 
             (UPPER(SIMPLIFIED_TITLE) LIKE 'SALES%' AND UPPER(SIMPLIFIED_TITLE) LIKE 'MANAGER%') OR 
             (UPPER(SIMPLIFIED_TITLE) LIKE '%SALES%' AND UPPER(SIMPLIFIED_TITLE) LIKE '%MANAGER%')
		THEN 'Sales Manager'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'OPERATIONS MANAGER' OR 
			 UPPER(SIMPLIFIED_TITLE) LIKE 'BUSINESS OPERATIONS MANAGER' OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'BUSINESS OPERATIONS%MANAGER%' OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'BUSINESS OPERATIONS MANAGER'  OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%OPERATIONS%MANAGER' OR
             UPPER(SIMPLIFIED_TITLE) LIKE '%OPERATIONS%MANAGER' 
		THEN 'Operations Manager'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'OPERATIONS MANAGER' OR 
			 
             UPPER(SIMPLIFIED_TITLE) LIKE 'BUSINESS OPERATIONS MANAGER%' 
		THEN 'Operations Manager'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'SHIELD EMERGING LEADER'
        THEN 'Shield Emerging Leader'
		WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'BUSINESS ANALYTICS MANAGER' OR
			 UPPER(SIMPLIFIED_TITLE) LIKE  'ANALYTICS MANAGER'
		THEN 'Analytics Manager' 
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'BUSINESS ANALYST' OR
			 UPPER(SIMPLIFIED_TITLE) LIKE 'SENIOR BUSINESS ANALYST' OR 
             UPPER(SIMPLIFIED_TITLE) LIKE 'SENIOR BUSINESS ANALYST%' OR 
             UPPER(SIMPLIFIED_TITLE) LIKE 'BUSINESS ANALYST%' OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'BUSINESS%' AND '%ANALYST' OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'BUSINESS DATA ANALYST' OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'BUSINESS INTELLIGENCE ANALYST' OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'BUSINESS INTELLIGENCE SPECIALIST' OR
             UPPER(SIMPLIFIED_TITLE) LIKE 'LEAD DATA ANALYST' OR
			UPPER(SIMPLIFIED_TITLE) LIKE 'DATA ANALYST'
        THEN 'Business/Data Analyst'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE '%ANALYST%'
        THEN 'Other Analyst'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE 'MANAGER %' OR
			 UPPER(SIMPLIFIED_TITLE) LIKE 'MANAGER, %'
        THEN 'Manager'
        WHEN UPPER(SIMPLIFIED_TITLE) LIKE '%MANAGER%'
        THEN 'Other Manager'
		ELSE TITLE_GROUP
    END AS TITLE_MAIN
FROM 
	CTE
WHERE
	post_grad=0
)
SELECT
	row_number() over(order by handle) as row_num ,
    CTE_INDICATORS.*
FROM 
	CTE_INDICATORS
WHERE
	YEAR(CMBND_GRAD) != 2023
    AND YEAR(CMBND_GRAD) >= 2000
;


    
